name: "Terraform Apply"

on:
  push:
    branches:
      - main

env:
  TF_CLOUD_ORGANIZATION: "zwell-test"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  BUILD_VERSION: "${{ github.sha }}"
  TF_WORKSPACE: "dev-test"
  CONFIG_DIRECTORY: "./terraform/"
  AWS_DEFAULT_REGION: "us-west-2"

jobs:
  # builds and pushes image to ecr
  docker:
    name: "Build and Push Image"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

        # configure pipeline login for ecr
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: ${{ secrets.aws_account_id }}
          mask-password: "true"

        # Build image and tag
        # Push to ECR
      - name: 'Build Image'
        shell: bash
        run: |
          image_tag="${{env.BUILD_VERSION}}"
          docker build -t ${{secrets.ecr_registry}}:${image_tag} -f ./Dockerfile.lambda --platform linux/arm64 .
          docker push ${{secrets.ecr_registry}}:${image_tag}

  terraform:
    name: "Terraform Apply"
    needs: docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # Gets the most current config (tf.plan) for org + workspace combo
      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.2.0
        id: apply-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}

        # runs changes in terrafrom/ against current state to create a tf.plan
        # tarraform plan
      - name: Create Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.2.0
        id: apply-run
        env:
          TF_VAR_image_tag: "\"${{ env.BUILD_VERSION }}\""
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}
          is_destroy: true

        # terraform apply the plan
      - name: Apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.2.0
        if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
        id: apply
        with:
          run: ${{ steps.apply-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"